name: Post-Merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  post-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Run linter
        run: |
          . .venv/bin/activate
          flake8 .
          black --check .

      - name: Run unit tests
        run: |
          . .venv/bin/activate
          coverage run -m unittest discover
          coverage report

      - name: Generate unit test report
        run: |
          . .venv/bin/activate
          coverage xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml