name: Post-Merge

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow'
        required: true
        default: 'development'

jobs:
  post-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run linter
        run: |
          flake8 .
          black --check .

      - name: Run unit tests
        run: |
          coverage run -m unittest discover test
          coverage report

      - name: Generate unit test report
        if: ${{ github.event.inputs.environment == 'production' }}
        run: |
          coverage xml

      - name: Upload coverage report
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml